#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xset r rate 350 20 &
$HOME/.config/polybar/launch.sh &
dunst -conf $HOME/.config/dunst/dunstrc &
picom &
feh --bg-fill ~/Pictures/hollow-knight.png &
ibus-daemon -drxR &
nm-applet &
setxkbmap -option caps:swapescape &
pgrep -x battery-alert > /dev/null || ~/bin/battery-alert &
pidof redshift || redshift -l "12:125" -t "6500:3200" &
pidof syncthing || syncthing -no-browser &
trash-empty -f 30 &
wmname LG3D &

bspc monitor -d 1 2 3 4 5 6 7
bspc config border_width         2
bspc config window_gap          17
bspc config focused_border_color \#ad8ee6
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a firefox desktop=^2
bspc rule -a discord desktop=^3
bspc config external_rules_command "$HOME/bin/spotify-rule"
