#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xset r rate 350 20 &
setxkbmap -option caps:swapescape &
$HOME/.config/polybar/launch.sh &
dunst -conf $HOME/.config/dunst/dunstrc &
picom &
feh --bg-fill ~/Pictures/hollow-knight.png &
xrdb merge ~/.Xresources &
ibus-daemon -drxR &
~/bin/battery-alert &

bspc monitor -d 1 2 3 4 5 6 7


bspc config border_width         0
bspc config window_gap          17
# bspc config border_radius	15

bspc config focused_border_color \#c0caf5

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a firefox desktop=^2
bspc rule -a discord desktop=^3
bspc config external_rules_command "$HOME/bin/spotify-rule"
